### ISSUE TITLE
ApplovinSDK & Cocoapods

### ISSUE THREAD

**Issue by hons82** [AppLovin/iOS-Demo-App#3]
Hi,
I'm currently tryin to integrate Applovin to my App by adding the SDK through [Cocoapods](https://cocoapods.org/?q=applovin), however it returns ```403 Forbidden```

```bash
Analyzing dependencies
Downloading dependencies
Installing AppLovin (3.0.2)

[!] Error installing AppLovin
[!] /usr/bin/curl -f -L -o /var/folders/h3/9p8v9rmj1t3f8gfsgkrt3p8m0000gn/T/d20150908-29048-nmw1c6/file.tbz http://sdk.applovin.com/applovin-ios-sdk-3.0.2.tar.bz2 --create-dirs

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0curl: (22) The requested URL returned error: 403 Forbidden
```

Is the cocoapods dependecy manager something that you do not support anymore?

~hons

**Comment by mszaro** [comment]
Hi Hons,

We have never actually supported Cocoapods - in fact the fact that there _is_ a pod is news to us. Please be aware that we don't maintain that nor have any idea what is inside it. We distribute only the .a from our website at http://applovin.com/integration and would prefer you pull the file from there.

Thanks

**Comment by hons82** [comment]
Interesting... and good to know :-)
btw the (integration guide)[https://www.applovin.com/integration#iosIntegration] on your website does not mention how to use your framework in swift

**Comment by mszaro** [comment]
Ah, we've just updated this repo with a swift demo app! Check it out :-)


    _____________________________
