### ISSUE TITLE
'ALNullabilityAnnotations.h' file not found

### ISSUE THREAD

**Issue by ggdiez** [AppLovin/iOS-Demo-App#5]
I just downloaded the code and added the last version of the library and headers and when I try to compile with xcode 7.2 the process failed. 

![captura de pantalla 2016-01-23 a las 21 35 43](https://cloud.githubusercontent.com/assets/2051473/12532650/4b906c22-c219-11e5-96b0-b060a207012e.png)

**Comment by mszaro** [comment]
Hi @ggdiez, this should be resolved now with commit https://github.com/AppLovin/iOS-Demo-App/commit/1d43664944450ff232286e3f3c4811aa4eb98d7e ... thanks for writing in!
