### ISSUE TITLE
Please add  swift documents

### ISSUE THREAD

**Issue by androidcn** [AppLovin/iOS-Demo-App#6]
Please add swift documents

**Comment by mszaro** [comment]
Hi there,

There is a full Swift example in this repository in the Swift/ sub folder, and simplified integration examples are posted on our website once you log in. Is there something specific you were looking for?

Thanks

**Comment by androidcn** [comment]
https://www.applovin.com/integration#iosRewardedVids
all the documents is objc

**Comment by mszaro** [comment]
Hi, this may be what you're looking for: https://github.com/AppLovin/iOS-Demo-App/blob/master/Swift%20Demo%20App/iOS-SDK-Demo/ALDemoRewardedVideosViewController.swift

Feel free to reopen the issue if we can help in any other way.

Thanks!

**Comment by androidcn** [comment]
thanks but i still hope to see swift document in your official webpage,and
this can help all the Swift iOS Developer
On Sat, Mar 12, 2016 at 2:35 PM Matt Szaro <notifications@github.com> wrote:

> Hi, this may be what you're looking for:
> https://github.com/AppLovin/iOS-Demo-App/blob/master/Swift%20Demo%20App/iOS-SDK-Demo/ALDemoRewardedVideosViewController.swift
>
> Feel free to reopen the issue if we can help in any other way.
>
> Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AppLovin/iOS-Demo-App/issues/6#issuecomment-195670792>
> .
>
-- 
能蟹仔

**Comment by mszaro** [comment]
I'll pass your feedback along 😄, thanks for writing in!
