### ISSUE TITLE
Suggest provide SDK Framework  or Cocoapods

### ISSUE THREAD

**Issue by androidcn** [AppLovin/iOS-Demo-App#7]
Suggest provide SDK Framework 
just like Google Mobile Ads SDK
https://developers.google.com/admob/ios/download?hl=zh-CN

and Cocoapods

**Comment by androidcn** [comment]
sorry  about that ..
i don't want to see  many header file ....

**Comment by mszaro** [comment]
Hi,

We provide you ALSwiftHeaders.h for this purpose 😁 if you add this one file to your Bridging Header, it will include all other SDK files you'll need. We're not on Cocoapods, but maybe that will help!

Thanks

**Comment by androidcn** [comment]
Thanks
On Sat, Mar 12, 2016 at 3:51 PM Matt Szaro <notifications@github.com> wrote:

> Hi,
>
> We provide you ALSwiftHeaders.h for this purpose 😁 if you add this one
> file to your Bridging Header, it will include all other SDK files you'll
> need. We're not on Cocoapods, but maybe that will help!
>
> Thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AppLovin/iOS-Demo-App/issues/7#issuecomment-195688881>
> .
>
-- 
能蟹仔
